# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/wanhsuan/cmake-3.24.2-linux-x86_64/bin/cmake

# The command to remove a file.
RM = /home/wanhsuan/cmake-3.24.2-linux-x86_64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/wanhsuan/OLSQ-dev

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/wanhsuan/OLSQ-dev

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/wanhsuan/cmake-3.24.2-linux-x86_64/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/wanhsuan/cmake-3.24.2-linux-x86_64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wanhsuan/OLSQ-dev/CMakeFiles /home/wanhsuan/OLSQ-dev//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wanhsuan/OLSQ-dev/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named olsq

# Build rule for target.
olsq: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 olsq
.PHONY : olsq

# fast build rule for target.
olsq/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/olsq.dir/build.make CMakeFiles/olsq.dir/build
.PHONY : olsq/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named olsqPy

# Build rule for target.
olsqPy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 olsqPy
.PHONY : olsqPy

# fast build rule for target.
olsqPy/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/olsqPy.dir/build.make CMakeFiles/olsqPy.dir/build
.PHONY : olsqPy/fast

app/main.o: app/main.cpp.o
.PHONY : app/main.o

# target to build an object file
app/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/app/main.cpp.o
.PHONY : app/main.cpp.o

app/main.i: app/main.cpp.i
.PHONY : app/main.i

# target to preprocess a source file
app/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/app/main.cpp.i
.PHONY : app/main.cpp.i

app/main.s: app/main.cpp.s
.PHONY : app/main.s

# target to generate assembly for a file
app/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/app/main.cpp.s
.PHONY : app/main.cpp.s

src/api/apiPy.o: src/api/apiPy.cpp.o
.PHONY : src/api/apiPy.o

# target to build an object file
src/api/apiPy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/olsq.dir/build.make CMakeFiles/olsq.dir/src/api/apiPy.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/olsqPy.dir/build.make CMakeFiles/olsqPy.dir/src/api/apiPy.cpp.o
.PHONY : src/api/apiPy.cpp.o

src/api/apiPy.i: src/api/apiPy.cpp.i
.PHONY : src/api/apiPy.i

# target to preprocess a source file
src/api/apiPy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/olsq.dir/build.make CMakeFiles/olsq.dir/src/api/apiPy.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/olsqPy.dir/build.make CMakeFiles/olsqPy.dir/src/api/apiPy.cpp.i
.PHONY : src/api/apiPy.cpp.i

src/api/apiPy.s: src/api/apiPy.cpp.s
.PHONY : src/api/apiPy.s

# target to generate assembly for a file
src/api/apiPy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/olsq.dir/build.make CMakeFiles/olsq.dir/src/api/apiPy.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/olsqPy.dir/build.make CMakeFiles/olsqPy.dir/src/api/apiPy.cpp.s
.PHONY : src/api/apiPy.cpp.s

src/cir/circuit.o: src/cir/circuit.cpp.o
.PHONY : src/cir/circuit.o

# target to build an object file
src/cir/circuit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/olsq.dir/build.make CMakeFiles/olsq.dir/src/cir/circuit.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/olsqPy.dir/build.make CMakeFiles/olsqPy.dir/src/cir/circuit.cpp.o
.PHONY : src/cir/circuit.cpp.o

src/cir/circuit.i: src/cir/circuit.cpp.i
.PHONY : src/cir/circuit.i

# target to preprocess a source file
src/cir/circuit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/olsq.dir/build.make CMakeFiles/olsq.dir/src/cir/circuit.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/olsqPy.dir/build.make CMakeFiles/olsqPy.dir/src/cir/circuit.cpp.i
.PHONY : src/cir/circuit.cpp.i

src/cir/circuit.s: src/cir/circuit.cpp.s
.PHONY : src/cir/circuit.s

# target to generate assembly for a file
src/cir/circuit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/olsq.dir/build.make CMakeFiles/olsq.dir/src/cir/circuit.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/olsqPy.dir/build.make CMakeFiles/olsqPy.dir/src/cir/circuit.cpp.s
.PHONY : src/cir/circuit.cpp.s

src/device/device.o: src/device/device.cpp.o
.PHONY : src/device/device.o

# target to build an object file
src/device/device.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/olsq.dir/build.make CMakeFiles/olsq.dir/src/device/device.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/olsqPy.dir/build.make CMakeFiles/olsqPy.dir/src/device/device.cpp.o
.PHONY : src/device/device.cpp.o

src/device/device.i: src/device/device.cpp.i
.PHONY : src/device/device.i

# target to preprocess a source file
src/device/device.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/olsq.dir/build.make CMakeFiles/olsq.dir/src/device/device.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/olsqPy.dir/build.make CMakeFiles/olsqPy.dir/src/device/device.cpp.i
.PHONY : src/device/device.cpp.i

src/device/device.s: src/device/device.cpp.s
.PHONY : src/device/device.s

# target to generate assembly for a file
src/device/device.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/olsq.dir/build.make CMakeFiles/olsq.dir/src/device/device.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/olsqPy.dir/build.make CMakeFiles/olsqPy.dir/src/device/device.cpp.s
.PHONY : src/device/device.cpp.s

src/misc/timeUsage.o: src/misc/timeUsage.cpp.o
.PHONY : src/misc/timeUsage.o

# target to build an object file
src/misc/timeUsage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/olsq.dir/build.make CMakeFiles/olsq.dir/src/misc/timeUsage.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/olsqPy.dir/build.make CMakeFiles/olsqPy.dir/src/misc/timeUsage.cpp.o
.PHONY : src/misc/timeUsage.cpp.o

src/misc/timeUsage.i: src/misc/timeUsage.cpp.i
.PHONY : src/misc/timeUsage.i

# target to preprocess a source file
src/misc/timeUsage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/olsq.dir/build.make CMakeFiles/olsq.dir/src/misc/timeUsage.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/olsqPy.dir/build.make CMakeFiles/olsqPy.dir/src/misc/timeUsage.cpp.i
.PHONY : src/misc/timeUsage.cpp.i

src/misc/timeUsage.s: src/misc/timeUsage.cpp.s
.PHONY : src/misc/timeUsage.s

# target to generate assembly for a file
src/misc/timeUsage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/olsq.dir/build.make CMakeFiles/olsq.dir/src/misc/timeUsage.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/olsqPy.dir/build.make CMakeFiles/olsqPy.dir/src/misc/timeUsage.cpp.s
.PHONY : src/misc/timeUsage.cpp.s

src/olsq/olsq.o: src/olsq/olsq.cpp.o
.PHONY : src/olsq/olsq.o

# target to build an object file
src/olsq/olsq.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/olsq.dir/build.make CMakeFiles/olsq.dir/src/olsq/olsq.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/olsqPy.dir/build.make CMakeFiles/olsqPy.dir/src/olsq/olsq.cpp.o
.PHONY : src/olsq/olsq.cpp.o

src/olsq/olsq.i: src/olsq/olsq.cpp.i
.PHONY : src/olsq/olsq.i

# target to preprocess a source file
src/olsq/olsq.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/olsq.dir/build.make CMakeFiles/olsq.dir/src/olsq/olsq.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/olsqPy.dir/build.make CMakeFiles/olsqPy.dir/src/olsq/olsq.cpp.i
.PHONY : src/olsq/olsq.cpp.i

src/olsq/olsq.s: src/olsq/olsq.cpp.s
.PHONY : src/olsq/olsq.s

# target to generate assembly for a file
src/olsq/olsq.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/olsq.dir/build.make CMakeFiles/olsq.dir/src/olsq/olsq.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/olsqPy.dir/build.make CMakeFiles/olsqPy.dir/src/olsq/olsq.cpp.s
.PHONY : src/olsq/olsq.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... olsq"
	@echo "... olsqPy"
	@echo "... app/main.o"
	@echo "... app/main.i"
	@echo "... app/main.s"
	@echo "... src/api/apiPy.o"
	@echo "... src/api/apiPy.i"
	@echo "... src/api/apiPy.s"
	@echo "... src/cir/circuit.o"
	@echo "... src/cir/circuit.i"
	@echo "... src/cir/circuit.s"
	@echo "... src/device/device.o"
	@echo "... src/device/device.i"
	@echo "... src/device/device.s"
	@echo "... src/misc/timeUsage.o"
	@echo "... src/misc/timeUsage.i"
	@echo "... src/misc/timeUsage.s"
	@echo "... src/olsq/olsq.o"
	@echo "... src/olsq/olsq.i"
	@echo "... src/olsq/olsq.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

